version: '3.8'

services:

  web:
    build: .
    container_name: odoo18
    user: root
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./data:/var/lib/odoo
      - ./filestore:/root/.local/share/Odoo/filestore  
      - ./logs:/var/log/odoo
      - ./kafka-addon:/mnt/extra-addons/kafka_integration:ro   
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo_password
      - OPENAI_API_KEY=votre_cle_api_openai
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:29092             
      - KAFKA_ENABLED=true                                     
    restart: unless-stopped
    command: odoo --dev=reload,qweb,werkzeug,xml
    networks:
       default :
       kafka-integration :

  db:
    image: postgres:15
    container_name: odoo18-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: odoo18-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - default

  # Service optionnel : installation de l'addon Kafka (si besoin)
  odoo-kafka-installer:
    image: alpine:latest
    container_name: odoo-kafka-installer
    volumes:
      - ../kafka-orchestrator/network-bridge/odoo-kafka-addon:/source:ro
      - ./kafka-addon:/destination
    command: |
      sh -c "
        echo '📦 Installation de l addon Kafka pour Odoo...'
        cp -r /source/* /destination/ 2>/dev/null || true
        echo '✅ Addon Kafka installé'
        "
    restart: "no"

volumes:
  postgresql:
  odoo-data:

networks:
  default:
  kafka-integration:
    name: kafka-integration-network